### ISSUE TITLE
[Bug] Issue with background of widget with themes

### ISSUE THREAD

**Issue by FallenDeity** [colbyfayock/next-cloudinary#243] opened 2023-07-25 12:39 UTC
# **Bug Report**

## Background Color Issue with CldWidget propagated from CldUploadButton

Light Mode

![image](https://github.com/colbyfayock/next-cloudinary/assets/61227305/eb195340-dc97-4d0b-9fa4-6957c532728d)

Dark Mode

![image](https://github.com/colbyfayock/next-cloudinary/assets/61227305/7eade984-9b77-4231-ba19-aae01a2327d8)

Also is there any way to change the css to remove the bg color?

## **Is this a regression?**

First time using

## **Steps To Reproduce the error**

Using tailwind css for theme handling along with next-themes

**Comment by colbyfayock** [comment] 2023-07-25 13:04
hey @FallenDeity can you help me to understand what's going on? I assume the issue is the background no longer visible moreso just simply a color

the issue stemming from light vs dark mode? are those custom configurations that you're setting?

can you recreate this in a codesandbox? that would help me debug easier

**Comment by colbyfayock** [comment] 2023-07-25 20:33
I was able to reproduce this, it's a strange one

i'm having a hard time telling if this is related to the Upload Widget or if it's a browser thing

Whats happening in the background is the widget is loading an iframe overlaid and it seems that the iframe is having the issue

the only thing i've found so far somewhat related is:

https://stackoverflow.com/questions/70352898/why-does-color-scheme-dark-cause-objects-to-have-white-backgrounds-in-chrom

in there, someone mentioned a fix of adding a style to set the color scheme of the object to light

so in this instance, setting:

```
iframe {
  color-scheme: light;
}
```

seems to fix it

still asking around to see if this is solvable on our side, but it may be a browser limitation? not sure

**Comment by FallenDeity** [comment] 2023-07-26 19:40
Yep that works ty!! Is there any way I can change color of the background when the widget pops up? perhaps some css variable globally?

**Comment by colbyfayock** [comment] 2023-07-28 01:33
awesome! Yup you can, unfortunately not CSS Variables, but under the styles.frame.background property, see for instance the code snippet here: https://cloudinary.com/documentation/upload_widget#look_and_feel_customization

you would pass that in under the options prop as i showed a bit earlier in the thread

going to close this issue but still happy to answer other questions!

**Closed by colbyfayock** 2023-07-28 01:33 UTC
