### ISSUE TITLE
[Bug] Setting controls to false on CldVideoPlayer does not disable controls

### ISSUE THREAD

**Issue by tecsobs** [colbyfayock/next-cloudinary#282] opened 2023-09-20 00:06 UTC
# **Bug Report**

## **Describe the bug**

Using the nextjs package and specifing controls = false, the video player keep showing the controls. 

This is my only import, i'm not importing any css

import { CldVideoPlayer } from 'next-cloudinary';

<CldVideoPlayer
          id='some-id'
          src='some/video'
          width='auto'
          height='auto'
          autoPlay='always'
          controls={false}
          logo={false}
/>

## **Steps To Reproduce the error**

1.
2.
3.
4.

## **Expected behaviour**

All controls should not be created on dom.

### **Your environment**

- OS: 
- Node version: v16.20.1
- Npm version: 8.19.4
- Browser name and version: Chrome

**Comment by Vaibhav91one** [comment] 2023-10-04 07:18
I would like to work on this issue.

**Comment by colbyfayock** [comment] 2023-10-04 12:15
hey @Vaibhav91one let's start with 1 issue at a time and we can start with this one, that way we can make sure others have an opportunity to work on an issue. if this is merged and the other is still available, i can assign that to you as well!

assigning this one to you

**Comment by colbyfayock** [comment] 2023-10-12 15:38
hey @Vaibhav91one are you still working on this?

**Comment by Vaibhav91one** [comment] 2023-10-12 16:13
Yes. Been a little busy with University. Will provide an update on 15.

**Comment by colbyfayock** [comment] 2023-10-12 16:15
sounds great, thanks @Vaibhav91one!

**Comment by colbyfayock** [comment] 2023-10-12 18:20
hey @tecsobs can you share the code to reproduce this? i was just trying to check if i could reproduce this and i was unable to with: 

```
<CldVideoPlayer
  id="basic"
  width="1620"
  height="1080"
  src={`${process.env.VIDEOS_DIRECTORY}/mountain-stars`}
  controls={false}
/>
```

when trying it inside of the docs

<img width="798" alt="image" src="https://github.com/colbyfayock/next-cloudinary/assets/1045274/d05ad6a5-5761-4e3f-b650-88ea4e4a6ec6">

i do think i see a bug however that doesnt allow me to autoplay with controls off, but that would be another bug issue to file if thats the case

**Comment by colbyfayock** [comment] 2023-10-29 18:37
closing due to no answer and can't reproduce

**Closed by colbyfayock** 2023-10-29 18:37 UTC
